version: '3.8'

services:
  # 1. Serviço MongoDB (Persistência)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  # 2. Serviço ZooKeeper 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  # 3. Serviço Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      # CORREÇÃO CRÍTICA: Permite replicação com 1 Broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      
      # O HOSTNAME usado pelos scripts Python (de fora do Docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    restart: always

    # 4. Serviço MinIO (Object Storage)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Porta da API
      - "9001:9001" # Porta do Console Web (Opcional, mas útil)
    environment:
      # Credenciais de acesso
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
      # Comando para iniciar o MinIO
      MINIO_SERVER_URL: http://localhost:9000
    command: server /data --console-address :9001
    volumes:
      - minio-data:/data
    restart: always

    # docker-compose.yml (Adicione estes serviços ao seu arquivo existente)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Mapeia o arquivo de configuração que você acabou de criar
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      # Porta padrão do Prometheus
      - "9090:9090"
    networks:
      - seu-network # Use a mesma network dos outros serviços (kafka, mongo)
    depends_on:
      - kafka # Depende do Kafka para garantir que a infraestrutura está pronta

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      # Porta padrão do Grafana
      - "3000:3000"
    networks:
      - seu-network
    # Grafana só é útil se o Prometheus estiver rodando
    depends_on:
      - prometheus

# Certifique-se de que sua network está definida (se você usou uma):
networks:
  seu-network:
    driver: bridge

# Definição dos volumes persistentes
volumes:
  mongo-data:  
  minio-data: